#!/usr/bin/env python3
"""Build the single-file ReFusion scene skill brief for external agents."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

SOURCES = [
    ("Skill Entry Point", "skills/refusion-skills/SKILL.md"),
    ("Scene Program JSON Rule", "skills/refusion-skills/rules/scene-program-json.md"),
    (
        "Professional Timing Contract Rule",
        "skills/refusion-skills/rules/professional-timing-contract.md",
    ),
    ("Choreography Rule", "skills/refusion-skills/rules/choreography.md"),
    ("Composition Workspace Rule", "skills/refusion-skills/rules/composition-workspace.md"),
    ("Transition Authoring Rule", "skills/refusion-skills/rules/transitions.md"),
    ("Capability Registry Rule", "skills/refusion-skills/rules/capability-registry.md"),
    ("Tutorial Intake Rule", "skills/refusion-skills/rules/tutorial-intake.md"),
    ("Validation Rule", "skills/refusion-skills/rules/validation.md"),
    (
        "Basic Typewriter Intro Example",
        "skills/refusion-skills/examples/basic-typewriter-intro.json",
    ),
]


def main() -> None:
    output = ROOT / "REFUSION_SCENE_SKILL_FULL.md"
    lines = [
        "# ReFusion Scene Skill Full Agent Brief",
        "",
        "This file is generated from the official ReFusion skill pack.",
        "Use it when an AI agent cannot browse repository folders or follow",
        "relative links such as `skills/refusion-skills/rules/*.md`.",
        "",
        "Do not edit this file directly. Update the source files and run:",
        "",
        "```bash",
        "python3 scripts/build_full_skill_bundle.py",
        "```",
        "",
        "## Included Sources",
        "",
    ]
    for _, rel_path in SOURCES:
        lines.append(f"- `{rel_path}`")
    lines.append("")

    for title, rel_path in SOURCES:
        source_path = ROOT / rel_path
        body = source_path.read_text(encoding="utf-8").strip()
        lines.extend(
            [
                "---",
                "",
                f"# {title}",
                "",
                f"Source: `{rel_path}`",
                "",
                body,
                "",
            ],
        )

    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
